### ISSUE TITLE
Training with aligned dataset

### ISSUE THREAD

**Issue by krummrey** [taesungp/contrastive-unpaired-translation#141]
I was trying to train with an aligned dataset. The default (unaligned training) works fine. However if I want to leverage the aligned feature of the set I get this error:

`!python train.py --dataroot $dataset_path --name $project_name --CUT_mode CUT --load_size $load_size --crop_size $crop_size --display_id 0 --dataset_mode aligned`
```
Traceback (most recent call last):
  File "train.py", line 10, in <module>
    opt = TrainOptions().parse()   # get training options
  File "/content/drive/MyDrive/colab-cut-test/CUT/options/base_options.py", line 143, in parse
    opt = self.gather_options()
  File "/content/drive/MyDrive/colab-cut-test/CUT/options/base_options.py", line 102, in gather_options
    dataset_option_setter = data.get_option_setter(dataset_name)
  File "/content/drive/MyDrive/colab-cut-test/CUT/data/__init__.py", line 43, in get_option_setter
    dataset_class = find_dataset_using_name(dataset_name)
  File "/content/drive/MyDrive/colab-cut-test/CUT/data/__init__.py", line 26, in find_dataset_using_name
    datasetlib = importlib.import_module(dataset_filename)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'data.aligned_dataset'
```
I'm using colab to train. Any help would be appreciated.

**Comment by taesungp** [comment]
Hi Krummrey, this repo does not aim to tackle the aligned setting. So we don't provide the aligned dataloader. You can take a look at pix2pix, or [Contrastive Feature Loss for Image Prediction](https://github.com/alexandonian/contrastive-feature-loss) that utilizes contrastive loss for paired translation.
