### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for ResnetGenerator

### ISSUE THREAD

**Issue by fnurkinali** [taesungp/contrastive-unpaired-translation#146]
I am trying to run test.py script but got this error. How to fix this? 

Thank you.

RuntimeError: Error(s) in loading state_dict for ResnetGenerator:
	Missing key(s) in state_dict: "model.4.weight", "model.4.bias", "model.7.filt", "model.8.weight", "model.8.bias", "model.11.filt", "model.12.conv_block.1.weight", "model.12.conv_block.1.bias", "model.12.conv_block.5.weight", "model.12.conv_block.5.bias", "model.21.filt", "model.22.weight", "model.22.bias", "model.25.filt", "model.26.weight", "model.26.bias", "model.30.weight", "model.30.bias". 
	Unexpected key(s) in state_dict: "SAB.conv1.weight", "SAB.conv2.weight", "SAB.conv3.weight", "model.4.conv1.weight", "model.4.conv2.weight", "model.4.conv3.weight", "model.5.weight", "model.5.bias", "model.8.filt", "model.9.weight", "model.9.bias", "model.12.filt", "model.21.conv_block.1.weight", "model.21.conv_block.1.bias", "model.21.conv_block.5.weight", "model.21.conv_block.5.bias", "model.22.filt", "model.23.weight", "model.23.bias", "model.26.filt", "model.27.weight", "model.27.bias", "model.31.weight", "model.31.bias".

**Comment by taesungp** [comment]
Are you sure the checkpoint is the one trained with out code? "SAB" sounds unfamiliar to me.

**Comment by junyanz** [comment]
This [FAQ](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/qa.md#runtimeerror-errors-in-loading-state_dict-812-671461-296) might be related to your issue.

**Comment by Octoroboto** [comment]
I am getting a similar error trying to test after successful training with GrumpyCat and my own dataset and the FAQ posted by junyanz does not appear to apply to me after a quick read (although I am not an expert). Any help is appreciated. Thank you. Error:

Traceback (most recent call last):
  File "/Users/adgenerator/CUT/test.py", line 57, in <module>
    model.setup(opt)               # regular setup: load and print networks; create schedulers
  File "/Users/adgenerator/CUT/models/base_model.py", line 99, in setup
    self.load_networks(load_suffix)
  File "/Users/adgenerator/CUT/models/base_model.py", line 224, in load_networks
    net.load_state_dict(state_dict)
  File "/Users/adgenerator/Library/Python/3.9/lib/python/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ResnetGenerator:
	Missing key(s) in state_dict: "model.1.weight", "model.1.bias", "model.4.weight", "model.4.bias", "model.7.filt", "model.8.weight", "model.8.bias", "model.11.filt", "model.12.conv_block.1.weight", "model.12.conv_block.1.bias", "model.12.conv_block.5.weight", "model.12.conv_block.5.bias", "model.13.conv_block.1.weight", "model.13.conv_block.1.bias", "model.13.conv_block.5.weight", "model.13.conv_block.5.bias", "model.14.conv_block.1.weight", "model.14.conv_block.1.bias", "model.14.conv_block.5.weight", "model.14.conv_block.5.bias", "model.15.conv_block.1.weight", "model.15.conv_block.1.bias", "model.15.conv_block.5.weight", "model.15.conv_block.5.bias", "model.16.conv_block.1.weight", "model.16.conv_block.1.bias", "model.16.conv_block.5.weight", "model.16.conv_block.5.bias", "model.17.conv_block.1.weight", "model.17.conv_block.1.bias", "model.17.conv_block.5.weight", "model.17.conv_block.5.bias", "model.18.conv_block.1.weight", "model.18.conv_block.1.bias", "model.18.conv_block.5.weight", "model.18.conv_block.5.bias", "model.19.conv_block.1.weight", "model.19.conv_block.1.bias", "model.19.conv_block.5.weight", "model.19.conv_block.5.bias", "model.20.conv_block.1.weight", "model.20.conv_block.1.bias", "model.20.conv_block.5.weight", "model.20.conv_block.5.bias", "model.21.filt", "model.22.weight", "model.22.bias", "model.25.filt", "model.26.weight", "model.26.bias", "model.30.weight", "model.30.bias". 
	Unexpected key(s) in state_dict: "module.model.1.weight", "module.model.1.bias", "module.model.4.weight", "module.model.4.bias", "module.model.7.filt", "module.model.8.weight", "module.model.8.bias", "module.model.11.filt", "module.model.12.conv_block.1.weight", "module.model.12.conv_block.1.bias", "module.model.12.conv_block.5.weight", "module.model.12.conv_block.5.bias", "module.model.13.conv_block.1.weight", "module.model.13.conv_block.1.bias", "module.model.13.conv_block.5.weight", "module.model.13.conv_block.5.bias", "module.model.14.conv_block.1.weight", "module.model.14.conv_block.1.bias", "module.model.14.conv_block.5.weight", "module.model.14.conv_block.5.bias", "module.model.15.conv_block.1.weight", "module.model.15.conv_block.1.bias", "module.model.15.conv_block.5.weight", "module.model.15.conv_block.5.bias", "module.model.16.conv_block.1.weight", "module.model.16.conv_block.1.bias", "module.model.16.conv_block.5.weight", "module.model.16.conv_block.5.bias", "module.model.17.conv_block.1.weight", "module.model.17.conv_block.1.bias", "module.model.17.conv_block.5.weight", "module.model.17.conv_block.5.bias", "module.model.18.conv_block.1.weight", "module.model.18.conv_block.1.bias", "module.model.18.conv_block.5.weight", "module.model.18.conv_block.5.bias", "module.model.19.conv_block.1.weight", "module.model.19.conv_block.1.bias", "module.model.19.conv_block.5.weight", "module.model.19.conv_block.5.bias", "module.model.20.conv_block.1.weight", "module.model.20.conv_block.1.bias", "module.model.20.conv_block.5.weight", "module.model.20.conv_block.5.bias", "module.model.21.filt", "module.model.22.weight", "module.model.22.bias", "module.model.25.filt", "module.model.26.weight", "module.model.26.bias", "module.model.30.weight", "module.model.30.bias". 
	
I am using the default testing command on the CUT github page either with the grumpycat dataset or my own except with python3 instead of python:

python3 test.py --dataroot ./datasets/grumpifycat --name grumpycat_CUT --CUT_mode CUT --phase train

**Comment by sylar123abc** [comment]
> Does it matter that the missing keys are model.x.xxxx and the unexpected keys are module.model.x.xxxx? W
> ould the addition of the module part cause this problem and how might I fix it?

Same issue here
