### ISSUE TITLE
Error during running train.py: ConnectionRefusedError: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by ErikValle** [taesungp/contrastive-unpaired-translation#161]
The error below appears after running `python train.py --dataroot ./datasets/grumpifycat --name grumpycat_CUT`

```
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/CUT/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/user/anaconda3/envs/CUT/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/user/anaconda3/envs/CUT/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/CUT/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/user/anaconda3/envs/CUT/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/user/anaconda3/envs/CUT/lib/python3.10/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/home/user/anaconda3/envs/CUT/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/user/anaconda3/envs/CUT/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/user/anaconda3/envs/CUT/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/user/anaconda3/envs/CUT/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/home/user/anaconda3/envs/CUT/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/home/user/anaconda3/envs/CUT/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/user/anaconda3/envs/CUT/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f9718dd39d0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/CUT/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/user/anaconda3/envs/CUT/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/user/anaconda3/envs/CUT/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9718dd39d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/CUT/lib/python3.10/site-packages/visdom/__init__.py", line 708, in _send
    return self._handle_post(
  File "/home/user/anaconda3/envs/CUT/lib/python3.10/site-packages/visdom/__init__.py", line 677, in _handle_post
    r = self.session.post(url, data=data)
  File "/home/user/anaconda3/envs/CUT/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/user/anaconda3/envs/CUT/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/anaconda3/envs/CUT/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/user/anaconda3/envs/CUT/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9718dd39d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[Errno 111] Connection refused
Visdom.setup_socket.<locals>.on_close() takes 1 positional argument but 3 were given

Could not connect to Visdom server. 
 Trying to start a server....
Command: /home/user/anaconda3/envs/CUT/bin/python -m visdom.server -p 8097 &>/dev/null &
create web directory ./checkpoints/grumpycat_CUT/web...
/home/user/anaconda3/envs/CUT/lib/python3.10/site-packages/torchvision/transforms/transforms.py:329: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  warnings.warn(
/home/user/anaconda3/envs/CUT/lib/python3.10/site-packages/torchvision/transforms/transforms.py:329: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  warnings.warn(
/home/user/anaconda3/envs/CUT/lib/python3.10/site-packages/torchvision/transforms/transforms.py:329: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  warnings.warn(
/home/user/anaconda3/envs/CUT/lib/python3.10/site-packages/torchvision/transforms/transforms.py:329: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  warnings.warn(
/home/user/Documents/CUT/models/networks.py:569: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  patch_id = torch.tensor(patch_id, dtype=torch.long, device=feat.device)
---------- Networks initialized -------------
[Network G] Total number of parameters : 11.378 M
[Network F] Total number of parameters : 0.560 M
[Network D] Total number of parameters : 2.765 M
-----------------------------------------------
```

**Comment by ErikValle** [comment]
Solved, I added the option `--display_id -1` 
```
python train.py --dataroot ./datasets/grumpifycat --name grumpycat_CUT --display_id -1
```

**Comment by git1120201169hub** [comment]
@ErikValle Thanks! That helps a lot!!!
