### ISSUE TITLE
EOFError and Attribute error when attempting to train FastCUT

### ISSUE THREAD

**Issue by jamesdsmith99** [taesungp/contrastive-unpaired-translation#37]
I am trying train FastCUT on the horse2zebra dataset. However, it crashes giving an Attribute error and an EOFError. I have included the options that I am using to run train.py below as well as the stack trace:

```
python train.py --dataroot "./datasets/horse2zebra" --name H2Z_FAST_CUT --CUT_mode FastCUT
----------------- Options ---------------
                 CUT_mode: FastCUT                              [default: CUT]
               batch_size: 1
                    beta1: 0.5
                    beta2: 0.999
          checkpoints_dir: ./checkpoints
           continue_train: False
                crop_size: 256
                 dataroot: ./datasets/horse2zebra               [default: placeholder]
             dataset_mode: unaligned
                direction: AtoB
              display_env: main
             display_freq: 400
               display_id: None
            display_ncols: 4
             display_port: 8097
           display_server: http://localhost
          display_winsize: 256
               easy_label: experiment_name
                    epoch: latest
              epoch_count: 1
          evaluation_freq: 5000
        flip_equivariance: True
                 gan_mode: lsgan
                  gpu_ids: 0
                init_gain: 0.02
                init_type: xavier
                 input_nc: 3
                  isTrain: True                                 [default: None]
               lambda_GAN: 1.0
               lambda_NCE: 10.0
                load_size: 286
                       lr: 0.0002
           lr_decay_iters: 50
                lr_policy: linear
         max_dataset_size: inf
                    model: cut
                 n_epochs: 150
           n_epochs_decay: 50
               n_layers_D: 3
                     name: H2Z_FAST_CUT                         [default: experiment_name]
                    nce_T: 0.07
                  nce_idt: False
nce_includes_all_negatives_from_minibatch: False
               nce_layers: 0,4,8,12,16
                      ndf: 64
                     netD: basic
                     netF: mlp_sample
                  netF_nc: 256
                     netG: resnet_9blocks
                      ngf: 64
             no_antialias: False
          no_antialias_up: False
               no_dropout: True
                  no_flip: False
                  no_html: False
                    normD: instance
                    normG: instance
              num_patches: 256
              num_threads: 4
                output_nc: 3
                    phase: train
                pool_size: 0
               preprocess: resize_and_crop
          pretrained_name: None
               print_freq: 100
         random_scale_max: 3.0
             save_by_iter: False
          save_epoch_freq: 5
         save_latest_freq: 5000
           serial_batches: False
stylegan2_G_num_downsampling: 1
                   suffix:
         update_html_freq: 1000
                  verbose: False
----------------- End -------------------
dataset [UnalignedDataset] was created
model [CUTModel] was created
The number of training images = 1334
Setting up a new session...
create web directory ./checkpoints\H2Z_FAST_CUT\web...
Traceback (most recent call last):
  File "train.py", line 31, in <module>
    for i, data in enumerate(dataset):  # inner loop within one epoch
  File "D:\Style Transfer\contrastive-unpaired-translation-master\data\__init__.py", line 95, in __iter__
    for i, data in enumerate(self.dataloader):
  File "C:\Users\James\anaconda3\envs\styletransfer\lib\site-packages\torch\utils\data\dataloader.py", line 291, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\James\anaconda3\envs\styletransfer\lib\site-packages\torch\utils\data\dataloader.py", line 737, in __init__
    w.start()
  File "C:\Users\James\anaconda3\envs\styletransfer\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\James\anaconda3\envs\styletransfer\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\James\anaconda3\envs\styletransfer\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\James\anaconda3\envs\styletransfer\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\James\anaconda3\envs\styletransfer\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Visdom.setup_socket.<locals>.run_socket'

(styletransfer) D:\Style Transfer\contrastive-unpaired-translation-master>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\James\anaconda3\envs\styletransfer\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\James\anaconda3\envs\styletransfer\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

I get the same errors when I try to train the regular CUT model. It also may be worth noting that I can train CycleGAN with no issues.

I am running on windows, with Anaconda. I am using python version `3.7.7` and pytorch version `1.6.0`.

**Comment by ilpoli** [comment]
set --num_threads 0, it looks like there is an issue with num threads.

**Comment by jamesdsmith99** [comment]
This seems to fix the issue, the model is now training.

**Comment by sicongzhao** [comment]
> set --num_threads 0, it looks like there is an issue with num threads.

Thanks for sharing! It works.
