### ISSUE TITLE
Can this code run on Windows

### ISSUE THREAD

**Issue by wangjt1216** [taesungp/contrastive-unpaired-translation#52]

**Comment by JunlinHan** [comment]
I can't run it on windows. Though CycleGAN[https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix] works fine. 
I haven't figure out the reason yet.

**Comment by dr-benway** [comment]
code runs perfectly (on W10)

**Comment by pureYioYi** [comment]
> code runs perfectly (on W10)

Hello, dr

I test this code in ubuntu and it works pretty well, but when I try it on win10 with the same python env, i meet some problem:

`Could not connect to Visdom server.
 Trying to start a server....
Command: D:\SDKs\Python\Anaconda\envs\cut\python.exe -m visdom.server -p 8097 &>/dev/null &
create web directory ./checkpoints\singleimage_monet_etretat\web...
Traceback (most recent call last):
  File "train.py", line 31, in <module>
    for i, data in enumerate(dataset):  # inner loop within one epoch
  File "D:\Code\Python\CUT\data\__init__.py", line 95, in __iter__
    for i, data in enumerate(self.dataloader):
  File "D:\SDKs\Python\Anaconda\envs\cut\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "D:\SDKs\Python\Anaconda\envs\cut\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
    w.start()
  File "D:\SDKs\Python\Anaconda\envs\cut\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "D:\SDKs\Python\Anaconda\envs\cut\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\SDKs\Python\Anaconda\envs\cut\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\SDKs\Python\Anaconda\envs\cut\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\SDKs\Python\Anaconda\envs\cut\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'pytorch_wrap.<locals>.result'

(cut) D:\Code\Python\CUT>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\SDKs\Python\Anaconda\envs\cut\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\SDKs\Python\Anaconda\envs\cut\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input`

Python envs:
`
Python = 3.6.12
pytorch=1.4.0
torchvision==0.5.0
visdom==0.1.8
packaging
GPUtil==1.4.0
`

it seems to visdom does not work well. Could you please tell me how to solve this problem?
Thanks!

**Comment by Steedalion** [comment]
I had the same problem. It's related to pytorch windows thread issues. To solve go to `data/__init__.py` and
change the number of worker threads (line 79).

```self.dataloader = torch.utils.data.DataLoader(
            self.dataset,
            batch_size=opt.batch_size,
            shuffle=not opt.serial_batches,
            # num_workers=int(opt.num_threads), This is the problem, change it to 0
            num_workers = int(0), 
            drop_last=True if opt.isTrain else False,`

**Comment by Steedalion** [comment]
Duplicate of #37

**Comment by pureYioYi** [comment]
> I had the same problem. It's related to pytorch windows thread issues. To solve go to `data/__init__.py` and
> change the number of worker threads (line 79).
> 
> ```
>             self.dataset,
>             batch_size=opt.batch_size,
>             shuffle=not opt.serial_batches,
>             # num_workers=int(opt.num_threads), This is the problem, change it to 0
>             num_workers = int(0), 
>             drop_last=True if opt.isTrain else False,`
> ```
> 
> ![](chrome-extension://mdcffelghikdiafnfodjlgllenhlnejl/icons/copy.png)

Thanks！ Solved!
