### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by ajisaasai** [taesungp/contrastive-unpaired-translation#93]
I get the following error.
Please help me.
```
Traceback (most recent call last):
  File "I:\TEST\CUT\train.py", line 32, in <module>
    for i, data in enumerate(dataset):  # inner loop within one epoch
  File "I:\TEST\CUT\data\__init__.py", line 95, in __iter__
    for i, data in enumerate(self.dataloader):
  File "C:\Users\nuke\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "C:\Users\nuke\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\nuke\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "C:\Users\nuke\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\nuke\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\nuke\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\nuke\AppData\Local\Programs\Python\Python39\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\nuke\AppData\Local\Programs\Python\Python39\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'Visdom.setup_socket.<locals>.run_socket'

I:\TEST\CUT>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\nuke\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\nuke\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

**Comment by seewhyjay** [comment]
If you haven't solved it yet, I had the same issue but managed to fix it with [this](https://github.com/taesungp/contrastive-unpaired-translation/issues/52#issuecomment-747135015)

**Comment by taesungp** [comment]
Thank you for suggesting a fix!

**Comment by d19at001** [comment]
> Nếu bạn chưa giải quyết được thì tôi cũng gặp sự cố tương tự nhưng đã tìm cách khắc phục bằng [cách này](https://github.com/taesungp/contrastive-unpaired-translation/issues/52#issuecomment-747135015)

hi where are location data/__init__.py bro

**Comment by jjeffery17** [comment]
> > Nếu bạn chưa giải quyết được thì tôi cũng gặp sự cố tương tự nhưng đã tìm cách khắc phục bằng [cách này](https://github.com/taesungp/contrastive-unpaired-translation/issues/52#issuecomment-747135015)
> 
> hi where are location data/**init**.py bro

It is in the library of multiprocessing

C:\Users\YOUR-NAME\AppData\Local\Programs\Python\Python310\Lib\multiprocessing

Hope this helps :)
